[versions]
kotlin = "2.1.0"
arrow-vector = "18.1.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
arrow-vector = { module = "org.apache.arrow:arrow-vector", version.ref = "arrow-vector" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
